@startuml SmartHomeContainer
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml


AddElementTag("microService", $shape=EightSidedShape(), $bgColor="CornflowerBlue", $fontColor="white", $legendText="micro service\neight sided")
AddElementTag("storage", $shape=RoundedBoxShape(), $bgColor="lightSkyBlue", $fontColor="white")

SHOW_PERSON_OUTLINE()

Person(authUser, "Authorized User", "Authorized User system")

System_Boundary(smartHome, "SmartHome"){
    Container(webApp, "Web Application", "Go, ReactJS", "")
    Container(userService, "User service", "Go", "User management", $tags = "microService")
    Container(deviceService, "Device service", "Go", "Device management", $tags = "microService")
    Container(bus, "Device Message Bus", "RabbitMQ", "Transport events between application and devices")
    !include ../commons.puml!appDB
}

Rel_D(authUser, webApp, "Uses", "HTTPS")
Rel_D(webApp, userService, "Uses", "HTTPS")
Rel_D(webApp, deviceService, "Uses", "HTTPS")
Rel(userService, appDB, "Stores user data in")
Rel(deviceService, appDB, "Stores device data in")
Rel(deviceService, bus, "Send device update events to")

SHOW_LEGEND()
@enduml